export const pathTracingViewportConfig = {
  bloom: {
    radius: 0.3,
    strength: 0.52,
    threshold: 1.05,
  },
  bounces: 8,
  denoise: {
    atrousPasses: 3,
    colorPhi: 0.24,
    depthPhi: 0.08,
    depthRelativePhi: 0.018,
    detailProtection: 0.82,
    enabled: true,
    fireflyClampSigma: 3,
    fireflyMinRatio: 2.4,
    materialPhi: 0.18,
    normalPhi: 0.08,
    transparencyProtection: 0.92,
  },
  emissionGain: 1,
  environmentFillIntensity: 0.22,
  filterGlossyFactor: 0.55,
  maxSamples: 128,
  maxSampleOptions: [128, 256, 512] as const,
  maxTextureSize: 1024,
  minSamples: 1,
  renderDelayMs: 0,
  toneMappingExposure: 1,
  tiles: [1, 1] as const,
}
