export const pathTracingViewportConfig = {
  bloom: {
    radius: 0.2,
    strength: 0.12,
    threshold: 1.05,
  },
  bounces: 8,
  denoise: {
    albedoFloor: 0.04,
    atrousPasses: 3,
    colorPhi: 0.24,
    depthPhi: 0.08,
    depthRelativePhi: 0.018,
    detailProtection: 0.82,
    diffuseBlend: 0.72,
    diffuseIlluminationPhi: 0.42,
    enabled: true,
    emissiveFireflyRecovery: {
      clampBlend: 0.9,
      compositeBoost: 0.42,
      darkReceiverHighLuminance: 0.42,
      darkReceiverLowLuminance: 0.08,
      diffuseBlendBoost: 0.34,
      enabled: true,
      extremeEmissionLuminance: 9,
      localDensityMin: 0.055,
      localMinLuminance: 0.18,
      localMinRatio: 2.1,
      localSigma: 2.2,
      neighborReject: 0.92,
      rawProtectionReduction: 0.58,
      receiverMetalnessMax: 0.25,
      receiverRoughnessMin: 0.5,
      sceneRiskThreshold: 0.16,
      smallEmitterAreaRatio: 0.035,
      strongEmissionLuminance: 1.35,
      wideEmitterAreaRatio: 0.22,
    },
    fireflyClampSigma: 3,
    fireflyMinRatio: 2.4,
    materialPhi: 0.18,
    normalPhi: 0.08,
    residualBlend: 0.55,
    transparencyInteriorProtection: 0.28,
    transparencyProtection: 0.92,
  },
  emissionGain: 1,
  environmentFillIntensity: 0.22,
  filterGlossyFactor: 0.55,
  maxSamples: 128,
  maxSampleOptions: [128, 256, 512] as const,
  maxTextureSize: 1024,
  minSamples: 1,
  renderDelayMs: 0,
  toneMappingExposure: 1,
  tiles: [1, 1] as const,
}
